"""
Astrowatch World Astrology -- multi-tradition chart gallery generator.

Produces ONE self-contained HTML file per entity: a "view one by one" panel
viewer (prev/next) cycling through every tradition's chart_visuals.py panel,
plus the full-horoscope narrative (reading_engine.generate_full_horoscope_
narrative) below it. No external assets, no build step -- open the file in a
browser and it works, same delivery convention as this project's other
webapps (astrowatch_kundli_studio.html, astrowatch_daily_predictions.html).

This module does not compute anything new -- it only assembles output already
produced by reading_engine.py and chart_visuals.py into one page.
"""
import html as html_escape_mod

from .reading_engine import build_chart_bundle, generate_full_horoscope_narrative, generate_detailed_reading
from .chart_visuals import build_gallery_panels
from .registry import build_registry

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: Georgia, serif; background: #efece4; margin: 0; padding: 0 0 60px 0; color: #222; }}
  header {{ background: #1f2a24; color: #f2ede0; padding: 28px 24px; }}
  header h1 {{ margin: 0 0 4px 0; font-size: 26px; }}
  header p {{ margin: 0; color: #cfc9b8; font-size: 13px; }}
  .wrap {{ max-width: 880px; margin: 0 auto; padding: 24px; }}
  .gallery {{ background: #fff; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.12); padding: 20px; }}
  .gallery-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }}
  .badge {{ display: inline-block; font-size: 11px; padding: 3px 9px; border-radius: 12px; font-weight: bold; }}
  .badge.computed {{ background: #d7ecd9; color: #235c2b; }}
  .badge.reference {{ background: #f2dede; color: #8a3a3a; }}
  .panel-title {{ font-size: 18px; font-weight: bold; }}
  .panel-frame {{ border: 1px solid #ddd; border-radius: 6px; overflow: hidden; background: #fafafa; text-align: center; }}
  .nav {{ display: flex; justify-content: space-between; align-items: center; margin-top: 14px; }}
  .nav button {{ font-family: Georgia, serif; font-size: 14px; padding: 8px 18px; border-radius: 6px; border: 1px solid #999;
                background: #f5f5f0; cursor: pointer; }}
  .nav button:hover {{ background: #e8e8de; }}
  .dots {{ text-align: center; margin-top: 10px; font-size: 12px; color: #888; }}
  .narrative {{ margin-top: 28px; background: #fff; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.12); padding: 24px 28px; }}
  .narrative h2 {{ margin-top: 0; font-size: 20px; }}
  .narrative p {{ line-height: 1.65; font-size: 15px; margin: 0 0 16px 0; }}
  .toggle-detailed {{ margin-top: 20px; }}
  .toggle-detailed summary {{ cursor: pointer; font-weight: bold; color: #444; }}
  pre.detailed {{ white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 12.5px;
                  background: #fbfaf6; padding: 16px; border-radius: 6px; border: 1px solid #ddd; }}
  footer {{ text-align: center; font-size: 12px; color: #999; margin-top: 30px; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>Multi-tradition chart gallery -- Unified World Astrology Knowledge System, Astrowatch</p>
</header>
<div class="wrap">
  <div class="gallery">
    <div class="gallery-header">
      <div class="panel-title" id="panelTitle"></div>
      <div id="panelBadge"></div>
    </div>
    <div class="panel-frame" id="panelFrame"></div>
    <div class="nav">
      <button onclick="prevPanel()">&larr; Previous</button>
      <span id="panelCounter" style="font-size:13px;color:#666;"></span>
      <button onclick="nextPanel()">Next &rarr;</button>
    </div>
    <div class="dots" id="panelDots"></div>
  </div>

  <div class="narrative">
    <h2>Full Horoscope Reading</h2>
    {narrative_html}
    <details class="toggle-detailed">
      <summary>Show full 15-section technical reading</summary>
      <pre class="detailed">{detailed_escaped}</pre>
    </details>
  </div>

  <footer>Generated by Astrowatch's world_astrology reading engine. See the detailed reading for full
  source/evidence-level disclosure of what is and isn't computed per tradition.</footer>
</div>

<script>
const panels = {panels_json};
let idx = 0;
function renderPanel() {{
  const p = panels[idx];
  document.getElementById('panelTitle').textContent = p.display_name;
  document.getElementById('panelBadge').innerHTML =
    '<span class="badge ' + (p.is_computed_chart ? 'computed">Computed chart' : 'reference">Reference card, not computed') + '</span>';
  document.getElementById('panelFrame').innerHTML = p.svg;
  document.getElementById('panelCounter').textContent = (idx+1) + ' / ' + panels.length;
  document.getElementById('panelDots').textContent = panels.map((pp,i) => i===idx ? '\\u25CF' : '\\u25CB').join(' ');
}}
function nextPanel() {{ idx = (idx+1) % panels.length; renderPanel(); }}
function prevPanel() {{ idx = (idx-1+panels.length) % panels.length; renderPanel(); }}
renderPanel();
</script>
</body>
</html>
"""


def _narrative_to_html(narrative: str) -> str:
    paras = narrative.split("\n\n")
    return "\n".join(f"<p>{html_escape_mod.escape(p)}</p>" for p in paras)


def build_gallery_html(
    entity_name: str, entity_type: str, inception_date: str,
    latitude: float, longitude: float, timezone_name: str,
    inception_time=None, as_of_date=None, field=None, corpus_context=None,
) -> str:
    import json as _json

    b = build_chart_bundle(entity_name, entity_type, inception_date, latitude, longitude,
                            timezone_name, inception_time, as_of_date)
    reg = build_registry()
    panels = build_gallery_panels(b, reg)
    narrative = generate_full_horoscope_narrative(
        entity_name, entity_type, inception_date, latitude, longitude, timezone_name,
        inception_time, as_of_date, field=field, corpus_context=corpus_context,
    )
    detailed = generate_detailed_reading(entity_name, entity_type, inception_date, latitude,
                                          longitude, timezone_name, inception_time, as_of_date)

    panels_json = _json.dumps([
        {"tradition_key": p.tradition_key, "display_name": p.display_name,
         "is_computed_chart": p.is_computed_chart, "svg": p.svg}
        for p in panels
    ])

    return PAGE_TEMPLATE.format(
        title=f"{entity_name} -- Multi-Tradition Astrology Gallery",
        narrative_html=_narrative_to_html(narrative),
        detailed_escaped=html_escape_mod.escape(detailed),
        panels_json=panels_json,
    )
